### ISSUE TITLE
Cannot upload top level component

### ISSUE THREAD

**Issue by modelb-jrs** [7BIndustries/sliderule-cli#39]
Client: Windows sr-cli

Attempting to run initial upload to https://github.com/modelb-llc/trrs-wssm and received the following error.

Done uploading component.
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

**Comment by jmwright** [comment]
@modelb-jrs How did you install git? Did you use an ssh link (git://) instead of an https link when prompted for the link to the repo?

**Comment by modelb-jrs** [comment]
Pretty sure I installed the official Windows git client. It was over a year ago, so I can’t be sure. 

I used the -u option and supplied an https format URL for the repo.

**Comment by jmwright** [comment]
Is it [this one](https://git-scm.com/download/win)? That's the only one I've used. If you're using a different one, I will test it directly. There is one or two other Windows git clients floating around, and I've had varied success in general with anything except the one I linked.

Can you try the ssh URL for your repo as well to help narrow down what the issue is? This could be related to #31 where the system can be asking for a username and password and that's not being passed back up the stack to the user. Using the ssh URL and disabling the passphrase on your ssh key should work-around that issue. It's annoying to have to do that, but I haven't gotten it fixed yet. If the https URL has already been set as your origin, you may have to adjust that manually using `git  remote set-url git@github.com:modelb-llc/trrs-wssm.git`

Also, if sliderule-rs only failed on the upload part, all the changes should be added and committed locally. What does `git status` show? Will the git version you're using let you do a manual `git push origin master` now?

**Comment by modelb-jrs** [comment]
Looks like that is the git package I am using (just a much older version - I will upgrade).

I will have to test out the ssh url later.  In the mean time, git status reports:

```
On branch master
nothing to commit, working tree clean
```

`git push origin master` worked for the https url when run manually.  So, looks like this is just the gobbled up password prompt.  I will work to switch to ssh url as soon as I can.

**Comment by jmwright** [comment]
@modelb-jrs I've started working on username and password handling. If you haven't yet, maybe hold off on manually setting the origin URL to ssh. I'll do a new release as soon as the feature is done. Hopefully that will be early next week.

**Comment by modelb-jrs** [comment]
I have not reset my origin URL yet. Happy to hold off for new releases.

**Comment by jmwright** [comment]
@modelb-jrs I should be putting out a new build later tonight that allows https user/pass authentication. I'll post here when it's available. The command you'll run is `sliderule-cli.exe login` from within the component directory. The first thing it will ask is for the URL of the repo. You'll re-enter the same URL that you used the first time you tried to upload. By having it ask for the URL again, it also allows you to switch to ssh later if you want. It will give you a warning that you really should be using ssh instead of https, but you can ignore that for now. After entering the https URL, you'll be asked to enter the GitHub username and password that has push access to the repo. If you have 2FA enabled, you'll need to [get a personal access token](https://github.com/settings/tokens) and use that for the password. As the warning I've added states, this method uses git's built-in method for storing the password in a URL, which stores the info in plain text in the .git/config file. Only your user or an admin should have access to that file if it's stored in your user's local account, so you should be ok as long as you don't zip the whole project up (.git directory included) and send it to someone. I think this change really improves the UX, but is still a security problem. I think there are other ways of handling the login info, but it will be a large project to make that happen. I wanted to at least get a workable solution in the meantime.

**Comment by jmwright** [comment]
@modelb-jrs Please try the [latest release](https://github.com/7BIndustries/sliderule-cli/releases/tag/v0.3.0).

**Comment by modelb-jrs** [comment]
@jmwright  
I just tried the latest release.  I was able to run sr login as described.  I then added a file to my component and ran sr upload.  The upload was successful (the new file appeared in the repo with my commit log message).  But, I also received the following error on the command prompt:

`error: could not write config file .git/config: Permission denied`

I tried re-running the upload command with -v to see if there is more detail I could get about the error.  But it did not fail on the subsequent upload.  I will keep you posted.

**Comment by jmwright** [comment]
@modelb-jrs Interesting. It had to be able to write to that file if your upload worked. You're on Windows, correct? Can you confirm you have the .\.git\config file in your component directory? If so, please open it in Notepad and check the "URL = ..." line to make sure the URL includes your username and password. Also, please right click on the config file, select Properties, and check the file permissions.

**Comment by modelb-jrs** [comment]
Confirmed the content of the URL field is correct.  And I have full permissions on the file.  *shrugs*

**Comment by jmwright** [comment]
@modelb-jrs I've been unable to reproduce this error on Windows 10. Did you update your git installation?

**Comment by modelb-jrs** [comment]
Not yet.  I will do that now.

**Comment by modelb-jrs** [comment]
Updated.

**Comment by jmwright** [comment]
Was the error repeatable before, and is it fixed now?

**Comment by modelb-jrs** [comment]
Sadly, it was not repeatable.  I will keep a watch out for it.

**Comment by jmwright** [comment]
I'm going to close this for now, and we can reopen if required.
